apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: messaging
  name: messaging
spec:
  lookupPolicy:
    local: false
  tags:
  - name: 0.3.2-13
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-13
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-14
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-14
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-1
    from:
      kind: DockerImage
      name: quay.io/hluong/iot-consumer:0.3.2-1
    importPolicy: {}
    referencePolicy:
      type: Local
