apiVersion: v1
kind: Service
metadata:
  labels:
    app: pushprox-client
  name: pushprox-client
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: pushprox-client
    deployment: pushprox-client
  sessionAffinity: None
  type: ClusterIP
