apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-4711-nwpath-0815-0816
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sa-mw-dach/manuela-gitops.git
    targetRevision: HEAD
    path: config/instances/app-4711/nwpath-machine-sensor-mqtt-messaging
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}