apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: manuela-quickstart-messaging-
  generation: 1
  name: manuela-quickstart-messaging
  namespace: manuela-quickstart-messaging
spec:
  targetNamespaces:
  - manuela-quickstart-messaging