apiVersion: v1
kind: Service
metadata:
  labels:
    application: pushprox-client
  name: argocd-prometheus-spoke-ocp4
spec:
  type: ExternalName
  externalName: prometheus-operated.argocd.svc
  selector: {}
