apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#configurations:
#- kustomizeconfig-deploymentconfig.yaml

resources:
- machine-sensor-1-deployment.yaml
- machine-sensor-2-deployment.yaml

configMapGenerator:
- name: machine-sensor-1
  envs: 
  - machine-sensor-1-configmap.properties
- name: machine-sensor-2
  envs: 
  - machine-sensor-2-configmap.properties