kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:image-builder'
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: manuela-ci
  - kind: ServiceAccount
    name: pipeline
    namespace: wrichter-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-builder'