apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: manuela-stormshift-odh
resources:
- anomaly-detection-namespace.yaml
- anomaly-detection-operatorgroup.yaml

bases:
- ../../../templates/manuela-openshift-prod/anomaly-detection
- ../../../templates/manuela-team-rolebindings

images:
- name: anomaly-detection
  newName: image-registry.openshift-image-registry.svc:5000/manuela-stormshift-odh/anomaly-detection
