apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    application: machine-sensor
  name: machine-sensor
spec:
  lookupPolicy:
    local: false
  tags:
  - name: 0.3.3-7
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.3-7
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-1
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.2-1
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-2
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.2-2
    importPolicy: {}
    referencePolicy:
      type: Local
