apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: manuela-quickstart-machine-sensor
resources:
- machine-sensor-namespace.yaml
bases:
#- github.com/sa-mw-dach/manuela-gitops/config/templates/manuela/machine-sensor
- ../../../templates/manuela-openshift/machine-sensor

patchesStrategicMerge:
- machine-sensor-1-deployment.yaml
- machine-sensor-2-deployment.yaml

configMapGenerator:
- name: machine-sensor-1
  behavior: merge
  envs:
  - machine-sensor-1-configmap.properties
- name: machine-sensor-2
  behavior: merge
  envs:
  - machine-sensor-2-configmap.properties


images:
- name: machine-sensor
  newName: quay.io/manuela/iot-software-sensor
  newTag: quickstart