apiVersion: v1
kind: Secret
metadata:
  name: prometheus-additional-scrape-configs
type: Opaque
stringData:
#https://prometheus.io/docs/prometheus/latest/federation/
#      

  prometheus-additional.yaml: |-
    - job_name: federate

      scrape_interval: 15s
      honor_labels: true
      metrics_path: '/federate'

      # proxy_url: http://pushprox-proxy:8080/
      proxy_url: http://pushprox-proxy-manuela-argocd-aggregator.apps.cluster-sing-e23f.sing-e23f.example.opentlc.com:8080/
      params:
        'match[]':
          - argocd_app_info
      static_configs:
      # - targets: ['prometheus-operated.argocd.svc:9090']
      - targets: ['pushprox-client.manuela-argocd-aggregator:9090']

#      scheme: https
#        tls_config: 
#          insecure_skip_verify: true
